# Skeleter Configuration File
# This file defines input variables, AWS Parameter Store mappings, and Git repository template processing rules.

# Optional: Input variables with default values (lowest precedence)
# These can be overridden by Parameter Store values or command-line arguments
input_variables:
  aws_region: "us-west-2"
  aws_studio_region: "us-east-1"
  env_name: "mike"
  service: "admin-game-os"  # Used in templated paths
  # config_path: "/path/to/alternative/config.yaml"  # Override config file path

# Optional: Map of variable names to AWS Systems Manager Parameter Store paths
# These parameters will be fetched with decryption enabled (medium precedence)
parameter_store_map:
  studio: "/admin-gw/{{ service}}/test"
  #db_password: "/production/database/master_password"
  #api_key: "/production/external_api/secret_key"

# Required: Map of GitHub repositories to their template files and output paths
# Each repository will be cloned, templates rendered, and a PR created with changes
templates_map:
  "git@github.com:platform/infra-devops.git":
    "helm/values/skeleton/services/{{ service }}/values.jinja": "helm/values/{{ service }}/{{ env_name }}.yaml"


# Optional: GitHub configuration for PR creation
github_config:
  # GitHub token for API access (can also be set via GITHUB_TOKEN env var)
  # token: "your_github_token_here"
  
  # PR behavior settings
  force_merge: false  # Set to true to auto-merge PRs without prompting
  
  # Default PR settings
  pr_title_prefix: "Skeleter: Update configuration"
  pr_body: "Automated configuration update generated by Skeleter"
  target_branch: "master"  # Base branch for PRs
